version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: tmuser
      MYSQL_PASSWORD: tmpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://db:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: tmuser
      DB_PASSWORD: tmpass
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      JWT_SECRET: super-secret-change-in-prod
      JWT_EXPIRATION_MS: 86400000
    ports:
      - "8080:8080"


